# version: '3.8'

# services:
#   api:
#     build:
#       context: ./API
#     container_name: api
#     ports:
#       - "32768:8080"
#     networks:
#       - shared

#   client:
#     build:
#       context: ./ApiTesterConsoleApp
#     container_name: apiclient
#     depends_on:
#       - api
#     networks:
#       - shared

# networks:
#   shared:
#     driver: bridge
version: '3.8'

services:
  api:
    build:
      context: ./API
    container_name: api
    ports:
      - "32768:8080"
    networks:
      - shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  client:
    build:
      context: ./ApiTesterConsoleApp
    container_name: apiclient
    depends_on:
      - api
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    driver: bridge
